#!/usr/bin/env node
// A delivery fleet of 8 vans receives a driver-assist software update (4.1.3 -> 4.2.0). Five
// install it at once; one fails and rolls back; one is out of coverage and reports three days
// later; one never reports. Each van signs its own records onboard and uploads them when it
// next connects. Then van-03 is in a collision, and everyone needs to know which software was
// running and whether its logs are intact. Finally a battery pack is traced from cell maker to
// recycler. All data here is generated by the demo.
//   node demo.mjs
import { genKeypair } from "./lib/keys.mjs";
import { signRecord, contentOf, registry } from "./lib/record.mjs";
import { campaign, commitVins, vinProof, onboard, fileFingerprint, batteryHandoff } from "./src/records.mjs";
import { verifyVehicle, softwareAt, campaignReport, verifyBattery } from "./src/verify.mjs";

const MIN = 60000, H = 60 * MIN, D = 24 * H, T0 = Date.parse("2026-09-01T00:00:00Z");
const ts = (t) => new Date(t).toISOString().slice(5, 16).replace("T", " ");

const carmaker = genKeypair();
const vans = Array.from({ length: 8 }, (_, i) => ({ vin: `DEMOVAN0000000${String(i + 1).padStart(3, "0")}`.slice(-17), name: `van-0${i + 1}`, kp: genKeypair() }));
const vehicles = registry(vans.map((v) => ({ id: v.vin, pub: v.kp.pub })));
const image = Buffer.from("sample driver-assist image 4.2.0");
const targets = commitVins(vans.map((v) => v.vin));
const c = campaign(carmaker, { campaignId: "DA-4.2.0", carmaker: "carmaker", imageHash: fileFingerprint(image), fromVersion: "4.1.3", toVersion: "4.2.0", targetsRoot: targets.root, targetCount: targets.count, issuedAt: T0 });
const campaigns = new Map([["DA-4.2.0", { record: c, proofs: new Map(vans.map((v) => [v.vin, vinProof(targets, v.vin)])) }]]);

// Each van signs onboard. van-03 also logs its driving day in 10-minute segments.
const segments = new Map();
const streams = vans.map((v, i) => {
  const ob = onboard(v.vin, v.kp);
  if (i === 7) return ob;                                      // never reports
  const at = i === 6 ? T0 + 3 * D : T0 + (i + 1) * H;          // van-07 out of coverage for days
  const base = { campaignId: "DA-4.2.0", imageHash: fileFingerprint(image), fromVersion: "4.1.3", toVersion: "4.2.0", verifiedAt: at };
  ob.update(i === 4 ? { ...base, installedAt: null, result: "rolled-back" } : { ...base, installedAt: at + 20 * MIN, result: "installed" });
  if (i === 2) {
    let t = T0 + 2 * D + 6 * H;
    for (let s = 0; s < 36; s++, t += 10 * MIN) {
      if (s === 20) { ob.gap({ from: t, to: t + 4 * MIN, reason: "logger restart" }); t += 4 * MIN; }
      const bytes = Buffer.from(`sample log segment ${s}: speed, steering, braking, assist state ... ${"x".repeat(200 + s)}`);
      segments.set(`seg-${s}`, bytes);
      ob.log({ segment: `seg-${s}`, from: t, to: t + 10 * MIN, fingerprint: fileFingerprint(bytes), bytes: bytes.length });
    }
  }
  return ob;
});

const verifyOne = (ob, extra = {}) => verifyVehicle(ob.chain, { vin: ob.vin, vehicles, campaigns, carmakerPub: carmaker.pub, baseVersion: "4.1.3", ...extra });
const results = streams.filter((s) => s.chain.length).map((s) => verifyOne(s));
const rep = campaignReport("DA-4.2.0", vans.map((v) => v.vin), results);
const nm = (vins) => vins.map((x) => vans.find((v) => v.vin === x).name).join(", ") || "none";
console.log(`Campaign DA-4.2.0 (4.1.3 -> 4.2.0), signed by the carmaker, ${targets.count} vans targeted`);
console.log(`  installed, proven by the van's own signature: ${rep.installed.length} (${nm(rep.installed)})`);
console.log(`  failed and rolled back: ${nm(rep.failed)}`);
console.log(`  no report yet: ${nm(rep.noReport)}`);
console.log(`  invalid records: ${nm(rep.invalid)}`);
console.log(`  van-07 reported ${ts(streams[6].chain[0].verifiedAt)}, three days after issue, from records signed onboard at install time\n`);

const crash = T0 + 2 * D + 9 * H + 17 * MIN;
const v3 = verifyOne(streams[2], { segments });
console.log(`Collision: van-03 at ${ts(crash)} UTC`);
console.log(`  van-03 records verified with the log files: ${v3.ok ? "PASS" : "FAIL " + JSON.stringify(v3.problems)} (${v3.records} records, chain unbroken)`);
console.log(`  software running at the time: ${softwareAt(v3, crash)} (installed ${ts(v3.timeline.at(-1).from)})`);
console.log(`  logger offline: ${v3.gaps.map((g) => `${ts(g.from)} for ${(g.to - g.from) / MIN} min, ${g.reason}`).join("; ")} (signed by the van, not hidden)`);

console.log("\nTampering:");
const attempt = (label, ob, mutate, extra = {}) => {
  const q = { ...ob, chain: structuredClone(ob.chain) }, segs = new Map(segments);
  mutate(q.chain, segs);
  const r = verifyOne(q, { segments: segs, ...extra });
  console.log(`  ${label.padEnd(56)} ${r.ok ? "NOT CAUGHT" : "caught: " + [...new Set(r.problems.map((x) => x.reason))].join(", ")}`);
};
const s3 = streams[2];
attempt("the log segment covering the collision is deleted", s3, (ch) => ch.splice(20, 1));
attempt("the collision segment's bytes are edited", s3, (ch, segs) => segs.set("seg-19", Buffer.from(segs.get("seg-19").toString().replace("braking", "BRAKING"))));
attempt("install date moved to after the collision, re-signed", s3, (ch) => { ch[0] = signRecord(vans[2].kp, { ...contentOf(ch[0]), installedAt: ch[0].installedAt + 3 * D }); });
attempt("records re-signed with another van's key", s3, (ch) => { ch.forEach((r, i) => { ch[i] = signRecord(vans[3].kp, contentOf(r)); }); });
attempt("van reports an image the carmaker never released", streams[1], (ch) => { ch[0] = signRecord(vans[1].kp, { ...contentOf(ch[0]), imageHash: fileFingerprint(Buffer.from("other image")) }); });
const fake = campaign(genKeypair(), { ...contentOf(c) });
attempt("campaign forged by someone other than the carmaker", streams[0], () => {}, { campaigns: new Map([["DA-4.2.0", { ...campaigns.get("DA-4.2.0"), record: fake }]]) });

// Battery passport: cell maker -> pack assembler -> carmaker -> fleet -> recycler.
const cos = ["cell-maker", "pack-assembler", "carmaker", "fleet-operator", "recycler"].map((id) => ({ id, kp: genKeypair() }));
const companies = registry(cos.map((x) => ({ id: x.id, pub: x.kp.pub })));
const bh = [];
cos.forEach((co, i) => bh.push(batteryHandoff(co.kp, { batteryId: "PACK-77-0412", from: i ? cos[i - 1].id : "origin", to: co.id, at: T0 + i * 300 * D, docs: [fileFingerprint(Buffer.from(`sample document ${i}`))], stateOfHealth: [null, null, 100, 97, 81][i], prev: i ? bh[i - 1].claimId : null })));
const b = verifyBattery(bh, { companies });
console.log(`\nBattery PACK-77-0412: ${b.steps.join(" -> ")}: ${b.ok ? "PASS" : "FAIL"}`);
const forgedB = structuredClone(bh); forgedB[3] = batteryHandoff(genKeypair(), { ...contentOf(bh[3]), stateOfHealth: 95 });
console.log(`  fleet operator record re-signed by a forger (health 97 shown as 95): ${verifyBattery(forgedB, { companies }).ok ? "NOT CAUGHT" : "caught: " + [...new Set(verifyBattery(forgedB, { companies }).problems.map((p) => p.reason))].join(", ")}`);
